// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6q_FvLi5al6qQsOY3BDMHlxtSBgQ-gjQ',
    appId: '1:1080669773868:web:971824010dc60b43437189',
    messagingSenderId: '1080669773868',
    projectId: 'pamoja-da193',
    authDomain: 'pamoja-da193.firebaseapp.com',
    storageBucket: 'pamoja-da193.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDYgSZCgc5n0Hw11ymy5C0LqEIQpiNK1s',
    appId: '1:1080669773868:android:6566881b2162629a437189',
    messagingSenderId: '1080669773868',
    projectId: 'pamoja-da193',
    storageBucket: 'pamoja-da193.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATAOmM0w6Rah9i67uP7Z1x-qkDMrTyxWk',
    appId: '1:1080669773868:ios:895e0bd0ef12e456437189',
    messagingSenderId: '1080669773868',
    projectId: 'pamoja-da193',
    storageBucket: 'pamoja-da193.firebasestorage.app',
    iosBundleId: 'com.example.pamoja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATAOmM0w6Rah9i67uP7Z1x-qkDMrTyxWk',
    appId: '1:1080669773868:ios:895e0bd0ef12e456437189',
    messagingSenderId: '1080669773868',
    projectId: 'pamoja-da193',
    storageBucket: 'pamoja-da193.firebasestorage.app',
    iosBundleId: 'com.example.pamoja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6q_FvLi5al6qQsOY3BDMHlxtSBgQ-gjQ',
    appId: '1:1080669773868:web:0e2992b02e2dc8d6437189',
    messagingSenderId: '1080669773868',
    projectId: 'pamoja-da193',
    authDomain: 'pamoja-da193.firebaseapp.com',
    storageBucket: 'pamoja-da193.firebasestorage.app',
  );
}
